name: Publish flake to FlakeHub

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to publish to FlakeHub"
        type: "string"
        required: true

jobs:
  publish-flakehub:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get git tag
        id: git-tag
        run: |
          if [ -z "$TAG" ]; then
            echo "::error::Could not determine git tag"
            exit 1
          fi
          echo "tag=$TAG" >>"$GITHUB_OUTPUT"
        env:
          TAG: ${{ inputs.tag || github.ref_name }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ format('refs/tags/{0}', steps.git-tag.outputs.tag) }}
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/flakehub-push@v6
        with:
          visibility: public
          name: loqusion/typix
          tag: ${{ steps.git-tag.outputs.tag }}
