name: Run flake checks
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
      - "ci*"

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: flake check
        run: nix flake check

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: check examples
        run: |
          set -euo pipefail
          for f in $(find ./examples -maxdepth 1 -mindepth 1 -type d | sort -u); do
            nix flake check --no-write-lock-file "$f"
          done
