name: Update flake lockfile
on:
  workflow_dispatch:
  schedule:
    - cron: "39 8 7,22 * *"

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: typst-nix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          commit-msg: "chore: update flake.lock"
          pr-title: "chore: update flake.lock"
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

          pr-labels: |
            dependencies
            automated
          nix-options: --accept-flake-config
      - name: Merge PR
        run: |
          gh pr merge --squash --delete-branch --auto "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          PR_NUMBER: ${{ steps.update.outputs.pull-request-number }}
